# Generated by Django 4.1.7 on 2023-06-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
