# Generated by Django 4.1.7 on 2023-06-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_phone_latitude_phone_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='phone',
            name='longitude',
        ),
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='phone',
            name='location',
            field=models.ImageField(blank=True, null=True, upload_to='locations/'),
        ),
    ]
