# Generated by Django 4.1.7 on 2023-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_phone_latitude_remove_phone_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
